# Generated by Django 3.2.3 on 2021-07-23 08:09

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=500, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
